/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.shibasis.bifrost

import org.gradle.api.JavaVersion
import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.Task

/**
 * A simple 'hello world' plugin.
 */
class BifrostPlugin: Plugin<Project> {
    override fun apply(project: Project) {
//        project.tasks.register("greeting") { task: Task ->
//            task.doLast {
//                println("Hello from plugin 'bifrost.plugin'")
//            }
//        }
    }
}

object BifrostVersion {

}

